[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app"]
src_paths = ["app", "tests"]

[tool.ruff]
line-length = 88
target-version = "py310"
src = ["app", "tests"]

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = []
